//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameRes.Formats.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class arcStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal arcStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameRes.Formats.Strings.arcStrings", typeof(arcStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive content is encrypted.
        ///Choose appropriate encryption scheme..
        /// </summary>
        public static string ArcEncryptedNotice {
            get {
                return ResourceManager.GetString("ArcEncryptedNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no encryption.
        /// </summary>
        public static string ArcNoEncryption {
            get {
                return ResourceManager.GetString("ArcNoEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric key.
        /// </summary>
        public static string INTLabelNumericKey {
            get {
                return ResourceManager.GetString("INTLabelNumericKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passphrase.
        /// </summary>
        public static string INTLabelPassphrase {
            get {
                return ResourceManager.GetString("INTLabelPassphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheme.
        /// </summary>
        public static string INTLabelScheme {
            get {
                return ResourceManager.GetString("INTLabelScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive directory is encrypted.
        ///Enter archive encryption key or choose
        ///predefined encryption scheme..
        /// </summary>
        public static string INTNotice {
            get {
                return ResourceManager.GetString("INTNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8-bit encryption key.
        /// </summary>
        public static string YPFLabelKey {
            get {
                return ResourceManager.GetString("YPFLabelKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive directory is encrypted.
        ///Enter archive encryption key..
        /// </summary>
        public static string YPFNotice {
            get {
                return ResourceManager.GetString("YPFNotice", resourceCulture);
            }
        }
    }
}
