//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameRes.Formats.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class arcStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal arcStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameRes.Formats.Strings.arcStrings", typeof(arcStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive contents might be encrypted,
        ///choose appropriate encryption scheme..
        /// </summary>
        public static string AGSMightBeEncrypted {
            get {
                return ResourceManager.GetString("AGSMightBeEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base archive.
        /// </summary>
        public static string AMIBaseArchive {
            get {
                return ResourceManager.GetString("AMIBaseArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New archive will also contain entries from the base archive..
        /// </summary>
        public static string AMIBaseTooltip {
            get {
                return ResourceManager.GetString("AMIBaseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select base archive.
        /// </summary>
        public static string AMIChooseBase {
            get {
                return ResourceManager.GetString("AMIChooseBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amaterasu Translations Muv-Luv archive.
        /// </summary>
        public static string AMIDescription {
            get {
                return ResourceManager.GetString("AMIDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files suitable for AMI archive found..
        /// </summary>
        public static string AMINoFiles {
            get {
                return ResourceManager.GetString("AMINoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string ArcDefault {
            get {
                return ResourceManager.GetString("ArcDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive content is encrypted.
        ///Choose appropriate encryption scheme..
        /// </summary>
        public static string ArcEncryptedNotice {
            get {
                return ResourceManager.GetString("ArcEncryptedNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32-bit hex number.
        /// </summary>
        public static string ArcHex32Bit {
            get {
                return ResourceManager.GetString("ArcHex32Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore encryption.
        /// </summary>
        public static string ArcIgnoreEncryption {
            get {
                return ResourceManager.GetString("ArcIgnoreEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image is encrypted..
        /// </summary>
        public static string ArcImageEncrypted {
            get {
                return ResourceManager.GetString("ArcImageEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no encryption.
        /// </summary>
        public static string ArcNoEncryption {
            get {
                return ResourceManager.GetString("ArcNoEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ArcReset {
            get {
                return ResourceManager.GetString("ArcReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose title or enter a password.
        /// </summary>
        public static string ArcTitleOrPassword {
            get {
                return ResourceManager.GetString("ArcTitleOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default file names encoding.
        /// </summary>
        public static string DefaultEncoding {
            get {
                return ResourceManager.GetString("DefaultEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption keys.
        /// </summary>
        public static string DPKKeys {
            get {
                return ResourceManager.GetString("DPKKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive contains encrypted scripts.
        ///Choose encryption scheme or enter a passphrase..
        /// </summary>
        public static string FJSYSNotice {
            get {
                return ResourceManager.GetString("FJSYSNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose title or enter a key.
        /// </summary>
        public static string GALChoose {
            get {
                return ResourceManager.GetString("GALChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to âge proprietary image format.
        /// </summary>
        public static string GRPDescription {
            get {
                return ResourceManager.GetString("GRPDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liar-soft proprietary script format.
        /// </summary>
        public static string GSCDescription {
            get {
                return ResourceManager.GetString("GSCDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image is encrypted.
        ///Choose appropriate encryption scheme..
        /// </summary>
        public static string GYUImageEncrypted {
            get {
                return ResourceManager.GetString("GYUImageEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose game executable file.
        /// </summary>
        public static string INTChooseExe {
            get {
                return ResourceManager.GetString("INTChooseExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypted archives creation is not implemented..
        /// </summary>
        public static string INTCreationNotice {
            get {
                return ResourceManager.GetString("INTCreationNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CatSystem2 engine resource archive.
        /// </summary>
        public static string INTDescription {
            get {
                return ResourceManager.GetString("INTDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check EXE.
        /// </summary>
        public static string INTExeButton {
            get {
                return ResourceManager.GetString("INTExeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable Files.
        /// </summary>
        public static string INTExeFiles {
            get {
                return ResourceManager.GetString("INTExeFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key not found within {0}..
        /// </summary>
        public static string INTKeyNotFound {
            get {
                return ResourceManager.GetString("INTKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric key should be a 32-bit hexadecimal integer.
        /// </summary>
        public static string INTKeyRequirement {
            get {
                return ResourceManager.GetString("INTKeyRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric key.
        /// </summary>
        public static string INTLabelNumericKey {
            get {
                return ResourceManager.GetString("INTLabelNumericKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &quot;Check EXE&quot; button to look for key within game executable file..
        /// </summary>
        public static string INTMessage1 {
            get {
                return ResourceManager.GetString("INTMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternatively, enter archive encryption key or choose one of the predefined encryption schemes..
        /// </summary>
        public static string INTMessage2 {
            get {
                return ResourceManager.GetString("INTMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive directory is encrypted..
        /// </summary>
        public static string INTNotice {
            get {
                return ResourceManager.GetString("INTNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string KCAPDefault {
            get {
                return ResourceManager.GetString("KCAPDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kogado game engine resource archive.
        /// </summary>
        public static string KogadoDescription {
            get {
                return ResourceManager.GetString("KogadoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption scheme.
        /// </summary>
        public static string LabelEncScheme {
            get {
                return ResourceManager.GetString("LabelEncScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passphrase.
        /// </summary>
        public static string LabelPassphrase {
            get {
                return ResourceManager.GetString("LabelPassphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheme.
        /// </summary>
        public static string LabelScheme {
            get {
                return ResourceManager.GetString("LabelScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liar-soft image archive.
        /// </summary>
        public static string LWGDescription {
            get {
                return ResourceManager.GetString("LWGDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive contains encrypted scripts.
        ///Choose encryption scheme or enter a passphrase..
        /// </summary>
        public static string MBLNotice {
            get {
                return ResourceManager.GetString("MBLNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive content is encrypted..
        /// </summary>
        public static string MCAEncryptedNotice {
            get {
                return ResourceManager.GetString("MCAEncryptedNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose title or enter a key.
        /// </summary>
        public static string MCGChoose {
            get {
                return ResourceManager.GetString("MCGChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8-bit encryption key.
        /// </summary>
        public static string MCGLabelKey {
            get {
                return ResourceManager.GetString("MCGLabelKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding file.
        /// </summary>
        public static string MsgAddingFile {
            get {
                return ResourceManager.GetString("MsgAddingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating checksum....
        /// </summary>
        public static string MsgCalculatingChecksum {
            get {
                return ResourceManager.GetString("MsgCalculatingChecksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressing index....
        /// </summary>
        public static string MsgCompressingIndex {
            get {
                return ResourceManager.GetString("MsgCompressingIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption key required for archive creation..
        /// </summary>
        public static string MsgCreationKeyRequired {
            get {
                return ResourceManager.GetString("MsgCreationKeyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption method not implemented.
        /// </summary>
        public static string MsgEncNotImplemented {
            get {
                return ResourceManager.GetString("MsgEncNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name extension too long..
        /// </summary>
        public static string MsgExtensionTooLong {
            get {
                return ResourceManager.GetString("MsgExtensionTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name is too long.
        /// </summary>
        public static string MsgFileNameTooLong {
            get {
                return ResourceManager.GetString("MsgFileNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name contains illegal characters.
        /// </summary>
        public static string MsgIllegalCharacters {
            get {
                return ResourceManager.GetString("MsgIllegalCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: image format not recognized..
        /// </summary>
        public static string MsgInvalidImageFormat {
            get {
                return ResourceManager.GetString("MsgInvalidImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid archive version specified..
        /// </summary>
        public static string MsgInvalidVersion {
            get {
                return ResourceManager.GetString("MsgInvalidVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name without extension..
        /// </summary>
        public static string MsgNoExtension {
            get {
                return ResourceManager.GetString("MsgNoExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of files exceedes archive limit..
        /// </summary>
        public static string MsgTooManyFiles {
            get {
                return ResourceManager.GetString("MsgTooManyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating index....
        /// </summary>
        public static string MsgUpdatingIndex {
            get {
                return ResourceManager.GetString("MsgUpdatingIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing index....
        /// </summary>
        public static string MsgWritingIndex {
            get {
                return ResourceManager.GetString("MsgWritingIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compress contents.
        /// </summary>
        public static string NPACompressContents {
            get {
                return ResourceManager.GetString("NPACompressContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nitro+ resource archive.
        /// </summary>
        public static string NPADescription {
            get {
                return ResourceManager.GetString("NPADescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption keys
        ///(required even if contents is not encrypted).
        /// </summary>
        public static string NPAKeys {
            get {
                return ResourceManager.GetString("NPAKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nitro+ Steins;Gate resource archive.
        /// </summary>
        public static string NPASteinsGateDescription {
            get {
                return ResourceManager.GetString("NPASteinsGateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NScripter game engine resource archive.
        /// </summary>
        public static string NSADescription {
            get {
                return ResourceManager.GetString("NSADescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default audio sampling rate.
        /// </summary>
        public static string ODNAudioSampleRate {
            get {
                return ResourceManager.GetString("ODNAudioSampleRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix Ogg files checksums.
        /// </summary>
        public static string OGGFixCrc {
            get {
                return ResourceManager.GetString("OGGFixCrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive type.
        /// </summary>
        public static string ONSArchiveType {
            get {
                return ResourceManager.GetString("ONSArchiveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression.
        /// </summary>
        public static string ONSCompression {
            get {
                return ResourceManager.GetString("ONSCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string ONSCompressionNone {
            get {
                return ResourceManager.GetString("ONSCompressionNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flying Shine resource archive.
        /// </summary>
        public static string PDDescription {
            get {
                return ResourceManager.GetString("PDDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scramble contents.
        /// </summary>
        public static string PDScrambleContents {
            get {
                return ResourceManager.GetString("PDScrambleContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use default encryption scheme.
        /// </summary>
        public static string QLIEDefaultScheme {
            get {
                return ResourceManager.GetString("QLIEDefaultScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load transparency data from RC8 bitmap.
        /// </summary>
        public static string RCTApplyMask {
            get {
                return ResourceManager.GetString("RCTApplyMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically combine incremental frames.
        /// </summary>
        public static string RCTOverlayFrames {
            get {
                return ResourceManager.GetString("RCTOverlayFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ren&apos;Py game engine archive.
        /// </summary>
        public static string RPADescription {
            get {
                return ResourceManager.GetString("RPADescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32-bit key.
        /// </summary>
        public static string RPALabelKey {
            get {
                return ResourceManager.GetString("RPALabelKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File resembles RPM resource archive,
        ///but encryption key guess failed.
        ///Choose appropriate encryption scheme..
        /// </summary>
        public static string RPMEncryptedNotice {
            get {
                return ResourceManager.GetString("RPMEncryptedNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amaterasu Translations Muv-Luv script file.
        /// </summary>
        public static string SCRDescription {
            get {
                return ResourceManager.GetString("SCRDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename encoding.
        /// </summary>
        public static string SGLabelEncoding {
            get {
                return ResourceManager.GetString("SGLabelEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hex number.
        /// </summary>
        public static string TooltipHex {
            get {
                return ResourceManager.GetString("TooltipHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum file name length
        ///(not including extension).
        /// </summary>
        public static string WARCLabelLength {
            get {
                return ResourceManager.GetString("WARCLabelLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liar-soft game resource archive.
        /// </summary>
        public static string XFLDescription {
            get {
                return ResourceManager.GetString("XFLDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compress contents.
        /// </summary>
        public static string XP3CompressContents {
            get {
                return ResourceManager.GetString("XP3CompressContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compress directory.
        /// </summary>
        public static string XP3CompressHeader {
            get {
                return ResourceManager.GetString("XP3CompressHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KiriKiri game engine resource archive.
        /// </summary>
        public static string XP3Description {
            get {
                return ResourceManager.GetString("XP3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive content could be encrypted.
        ///Choose appropriate encryption scheme..
        /// </summary>
        public static string XP3EncryptedNotice {
            get {
                return ResourceManager.GetString("XP3EncryptedNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string XP3LabelVersion {
            get {
                return ResourceManager.GetString("XP3LabelVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retain directory structure.
        /// </summary>
        public static string XP3RetainStructure {
            get {
                return ResourceManager.GetString("XP3RetainStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yu-Ris game engine resource archive.
        /// </summary>
        public static string YPFDescription {
            get {
                return ResourceManager.GetString("YPFDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8-bit encryption key.
        /// </summary>
        public static string YPFLabelKey {
            get {
                return ResourceManager.GetString("YPFLabelKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive version.
        /// </summary>
        public static string YPFLabelVersion {
            get {
                return ResourceManager.GetString("YPFLabelVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive directory is encrypted.
        ///Choose appropriate encryption scheme..
        /// </summary>
        public static string YPFNotice {
            get {
                return ResourceManager.GetString("YPFNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to guess.
        /// </summary>
        public static string YPFTryGuess {
            get {
                return ResourceManager.GetString("YPFTryGuess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive content is encrypted..
        /// </summary>
        public static string ZIPEncryptedNotice {
            get {
                return ResourceManager.GetString("ZIPEncryptedNotice", resourceCulture);
            }
        }
    }
}
