//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameRes.Formats.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NPAScheme {
            get {
                return ((string)(this["NPAScheme"]));
            }
            set {
                this["NPAScheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string XP3Scheme {
            get {
                return ((string)(this["XP3Scheme"]));
            }
            set {
                this["XP3Scheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4294967295")]
        public uint YPFKey {
            get {
                return ((uint)(this["YPFKey"]));
            }
            set {
                this["YPFKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::GameRes.Formats.CatSystem.IntEncryptionInfo INTEncryption {
            get {
                return ((global::GameRes.Formats.CatSystem.IntEncryptionInfo)(this["INTEncryption"]));
            }
            set {
                this["INTEncryption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool XP3CompressHeader {
            get {
                return ((bool)(this["XP3CompressHeader"]));
            }
            set {
                this["XP3CompressHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XP3CompressContents {
            get {
                return ((bool)(this["XP3CompressContents"]));
            }
            set {
                this["XP3CompressContents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int XP3Version {
            get {
                return ((int)(this["XP3Version"]));
            }
            set {
                this["XP3Version"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XP3RetainStructure {
            get {
                return ((bool)(this["XP3RetainStructure"]));
            }
            set {
                this["XP3RetainStructure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("shift-jis")]
        public string SGFileNameEncoding {
            get {
                return ((string)(this["SGFileNameEncoding"]));
            }
            set {
                this["SGFileNameEncoding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::GameRes.Formats.NScripter.Compression ONSCompression {
            get {
                return ((global::GameRes.Formats.NScripter.Compression)(this["ONSCompression"]));
            }
            set {
                this["ONSCompression"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AMIBaseArchive {
            get {
                return ((string)(this["AMIBaseArchive"]));
            }
            set {
                this["AMIBaseArchive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AMIUseBaseArchive {
            get {
                return ((bool)(this["AMIUseBaseArchive"]));
            }
            set {
                this["AMIUseBaseArchive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PDScrambleContents {
            get {
                return ((bool)(this["PDScrambleContents"]));
            }
            set {
                this["PDScrambleContents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("290")]
        public uint YPFVersion {
            get {
                return ((uint)(this["YPFVersion"]));
            }
            set {
                this["YPFVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1111638594")]
        public uint RPAKey {
            get {
                return ((uint)(this["RPAKey"]));
            }
            set {
                this["RPAKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NPACompressContents {
            get {
                return ((bool)(this["NPACompressContents"]));
            }
            set {
                this["NPACompressContents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1095188814")]
        public uint NPAKey1 {
            get {
                return ((uint)(this["NPAKey1"]));
            }
            set {
                this["NPAKey1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("555831124")]
        public uint NPAKey2 {
            get {
                return ((uint)(this["NPAKey2"]));
            }
            set {
                this["NPAKey2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int ARCNameLength {
            get {
                return ((int)(this["ARCNameLength"]));
            }
            set {
                this["ARCNameLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KCAPPassPhrase {
            get {
                return ((string)(this["KCAPPassPhrase"]));
            }
            set {
                this["KCAPPassPhrase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KCAPScheme {
            get {
                return ((string)(this["KCAPScheme"]));
            }
            set {
                this["KCAPScheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WARCScheme {
            get {
                return ((string)(this["WARCScheme"]));
            }
            set {
                this["WARCScheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string LPKScheme {
            get {
                return ((string)(this["LPKScheme"]));
            }
            set {
                this["LPKScheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NOAScheme {
            get {
                return ((string)(this["NOAScheme"]));
            }
            set {
                this["NOAScheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NOAPassPhrase {
            get {
                return ((string)(this["NOAPassPhrase"]));
            }
            set {
                this["NOAPassPhrase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("65432")]
        public uint DPKKey1 {
            get {
                return ((uint)(this["DPKKey1"]));
            }
            set {
                this["DPKKey1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1139247708")]
        public uint DPKKey2 {
            get {
                return ((uint)(this["DPKKey2"]));
            }
            set {
                this["DPKKey2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DPKLastScheme {
            get {
                return ((string)(this["DPKLastScheme"]));
            }
            set {
                this["DPKLastScheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MBLPassPhrase {
            get {
                return ((string)(this["MBLPassPhrase"]));
            }
            set {
                this["MBLPassPhrase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ISFScheme {
            get {
                return ((string)(this["ISFScheme"]));
            }
            set {
                this["ISFScheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte MCGLastKey {
            get {
                return ((byte)(this["MCGLastKey"]));
            }
            set {
                this["MCGLastKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RCTPassword {
            get {
                return ((string)(this["RCTPassword"]));
            }
            set {
                this["RCTPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RCTTitle {
            get {
                return ((string)(this["RCTTitle"]));
            }
            set {
                this["RCTTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NSAPassword {
            get {
                return ((string)(this["NSAPassword"]));
            }
            set {
                this["NSAPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NSATitle {
            get {
                return ((string)(this["NSATitle"]));
            }
            set {
                this["NSATitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RPMScheme {
            get {
                return ((string)(this["RPMScheme"]));
            }
            set {
                this["RPMScheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string QLIEScheme {
            get {
                return ((string)(this["QLIEScheme"]));
            }
            set {
                this["QLIEScheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string YPFScheme {
            get {
                return ((string)(this["YPFScheme"]));
            }
            set {
                this["YPFScheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Optimal")]
        public global::System.IO.Compression.CompressionLevel ZIPCompression {
            get {
                return ((global::System.IO.Compression.CompressionLevel)(this["ZIPCompression"]));
            }
            set {
                this["ZIPCompression"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("932")]
        public int ZIPEncodingCP {
            get {
                return ((int)(this["ZIPEncodingCP"]));
            }
            set {
                this["ZIPEncodingCP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AZScriptScheme {
            get {
                return ((string)(this["AZScriptScheme"]));
            }
            set {
                this["AZScriptScheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AGSTitle {
            get {
                return ((string)(this["AGSTitle"]));
            }
            set {
                this["AGSTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NCARCScheme {
            get {
                return ((string)(this["NCARCScheme"]));
            }
            set {
                this["NCARCScheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MEDScriptScheme {
            get {
                return ((string)(this["MEDScriptScheme"]));
            }
            set {
                this["MEDScriptScheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GALKey {
            get {
                return ((string)(this["GALKey"]));
            }
            set {
                this["GALKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MGPKTitle {
            get {
                return ((string)(this["MGPKTitle"]));
            }
            set {
                this["MGPKTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BELLTitle {
            get {
                return ((string)(this["BELLTitle"]));
            }
            set {
                this["BELLTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NPKScheme {
            get {
                return ((string)(this["NPKScheme"]));
            }
            set {
                this["NPKScheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TacticsArcPassword {
            get {
                return ((string)(this["TacticsArcPassword"]));
            }
            set {
                this["TacticsArcPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TacticsArcTitle {
            get {
                return ((string)(this["TacticsArcTitle"]));
            }
            set {
                this["TacticsArcTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GYUTitle {
            get {
                return ((string)(this["GYUTitle"]));
            }
            set {
                this["GYUTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PAZTitle {
            get {
                return ((string)(this["PAZTitle"]));
            }
            set {
                this["PAZTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EAGLSEncryption {
            get {
                return ((string)(this["EAGLSEncryption"]));
            }
            set {
                this["EAGLSEncryption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FJSYSPassword {
            get {
                return ((string)(this["FJSYSPassword"]));
            }
            set {
                this["FJSYSPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PCKTitle {
            get {
                return ((string)(this["PCKTitle"]));
            }
            set {
                this["PCKTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RCTOverlayFrames {
            get {
                return ((bool)(this["RCTOverlayFrames"]));
            }
            set {
                this["RCTOverlayFrames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RCTApplyMask {
            get {
                return ((bool)(this["RCTApplyMask"]));
            }
            set {
                this["RCTApplyMask"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeRequired {
            get {
                return ((bool)(this["UpgradeRequired"]));
            }
            set {
                this["UpgradeRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ZIPPassword {
            get {
                return ((string)(this["ZIPPassword"]));
            }
            set {
                this["ZIPPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OGGFixCrc {
            get {
                return ((bool)(this["OGGFixCrc"]));
            }
            set {
                this["OGGFixCrc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("65001")]
        public int PFSEncodingCP {
            get {
                return ((int)(this["PFSEncodingCP"]));
            }
            set {
                this["PFSEncodingCP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("44100")]
        public uint ODNAudioSampleRate {
            get {
                return ((uint)(this["ODNAudioSampleRate"]));
            }
            set {
                this["ODNAudioSampleRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("932")]
        public int NOAEncodingCP {
            get {
                return ((int)(this["NOAEncodingCP"]));
            }
            set {
                this["NOAEncodingCP"] = value;
            }
        }
    }
}
