//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameRes.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class garStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal garStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameRes.Strings.garStrings", typeof(garStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables various extensions, such as transparency support..
        /// </summary>
        public static string BMPExtensionsDesc {
            get {
                return ResourceManager.GetString("BMPExtensionsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable BMP format extensions.
        /// </summary>
        public static string BMPExtensionsText {
            get {
                return ResourceManager.GetString("BMPExtensionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPEG compression quality.
        /// </summary>
        public static string JPEGQualityText {
            get {
                return ResourceManager.GetString("JPEGQualityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is empty.
        /// </summary>
        public static string MsgFileIsEmpty {
            get {
                return ResourceManager.GetString("MsgFileIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is too large.
        /// </summary>
        public static string MsgFileTooLarge {
            get {
                return ResourceManager.GetString("MsgFileTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inappropriate encryption scheme.
        /// </summary>
        public static string MsgInvalidEncryption {
            get {
                return ResourceManager.GetString("MsgInvalidEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file name.
        /// </summary>
        public static string MsgInvalidFileName {
            get {
                return ResourceManager.GetString("MsgInvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file format.
        /// </summary>
        public static string MsgInvalidFormat {
            get {
                return ResourceManager.GetString("MsgInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown encryption scheme.
        /// </summary>
        public static string MsgUnknownEncryption {
            get {
                return ResourceManager.GetString("MsgUnknownEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file could not be opened as resource archive.
        /// </summary>
        public static string MsgUnknownFormat {
            get {
                return ResourceManager.GetString("MsgUnknownFormat", resourceCulture);
            }
        }
    }
}
