//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GARbro.GUI.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class guiStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal guiStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GARbro.GUI.Strings.guiStrings", typeof(guiStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract.
        /// </summary>
        public static string ButtonExtract {
            get {
                return ResourceManager.GetString("ButtonExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ButtonOK {
            get {
                return ResourceManager.GetString("ButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string CtxMenuClose {
            get {
                return ResourceManager.GetString("CtxMenuClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string CtxMenuCopy {
            get {
                return ResourceManager.GetString("CtxMenuCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create archive....
        /// </summary>
        public static string CtxMenuCreate {
            get {
                return ResourceManager.GetString("CtxMenuCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string CtxMenuCut {
            get {
                return ResourceManager.GetString("CtxMenuCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete.
        /// </summary>
        public static string CtxMenuDelete {
            get {
                return ResourceManager.GetString("CtxMenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse in _Explorer.
        /// </summary>
        public static string CtxMenuExplorer {
            get {
                return ResourceManager.GetString("CtxMenuExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract.
        /// </summary>
        public static string CtxMenuExtract {
            get {
                return ResourceManager.GetString("CtxMenuExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string CtxMenuOpen {
            get {
                return ResourceManager.GetString("CtxMenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string CtxMenuPaste {
            get {
                return ResourceManager.GetString("CtxMenuPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string CtxMenuRefresh {
            get {
                return ResourceManager.GetString("CtxMenuRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Rename.
        /// </summary>
        public static string CtxMenuRename {
            get {
                return ResourceManager.GetString("CtxMenuRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by.
        /// </summary>
        public static string CtxMenuSortBy {
            get {
                return ResourceManager.GetString("CtxMenuSortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string CtxMenuSortByName {
            get {
                return ResourceManager.GetString("CtxMenuSortByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string CtxMenuSortBySize {
            get {
                return ResourceManager.GetString("CtxMenuSortBySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string CtxMenuSortByType {
            get {
                return ResourceManager.GetString("CtxMenuSortByType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsorted.
        /// </summary>
        public static string CtxMenuUnsorted {
            get {
                return ResourceManager.GetString("CtxMenuUnsorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string HeaderName {
            get {
                return ResourceManager.GetString("HeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string HeaderSize {
            get {
                return ResourceManager.GetString("HeaderSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string HeaderType {
            get {
                return ResourceManager.GetString("HeaderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive format.
        /// </summary>
        public static string LabelArchiveFormat {
            get {
                return ResourceManager.GetString("LabelArchiveFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive name.
        /// </summary>
        public static string LabelArchiveName {
            get {
                return ResourceManager.GetString("LabelArchiveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive options.
        /// </summary>
        public static string LabelArchiveOptions {
            get {
                return ResourceManager.GetString("LabelArchiveOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract files from {0} to.
        /// </summary>
        public static string LabelExtractAllTo {
            get {
                return ResourceManager.GetString("LabelExtractAllTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract {0} to.
        /// </summary>
        public static string LabelExtractFileTo {
            get {
                return ResourceManager.GetString("LabelExtractFileTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Game Resource browser.
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit preview _window to image.
        /// </summary>
        public static string MenuFitWindow {
            get {
                return ResourceManager.GetString("MenuFitWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        public static string MenuOpen {
            get {
                return ResourceManager.GetString("MenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent files.
        /// </summary>
        public static string MenuRecent {
            get {
                return ResourceManager.GetString("MenuRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/hide main _menu bar.
        /// </summary>
        public static string MenuToggleMenuBar {
            get {
                return ResourceManager.GetString("MenuToggleMenuBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/hide _status bar.
        /// </summary>
        public static string MenuToggleStatusBar {
            get {
                return ResourceManager.GetString("MenuToggleStatusBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/hide _toolbar.
        /// </summary>
        public static string MenuToggleToolBar {
            get {
                return ResourceManager.GetString("MenuToggleToolBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        public static string MenuView {
            get {
                return ResourceManager.GetString("MenuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose files to extract.
        /// </summary>
        public static string MsgChooseFiles {
            get {
                return ResourceManager.GetString("MsgChooseFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete these files?.
        /// </summary>
        public static string MsgConfirmDeleteFiles {
            get {
                return ResourceManager.GetString("MsgConfirmDeleteFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating archive {0}.
        /// </summary>
        public static string MsgCreatingArchive {
            get {
                return ResourceManager.GetString("MsgCreatingArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted {0}.
        /// </summary>
        public static string MsgDeletedItem {
            get {
                return ResourceManager.GetString("MsgDeletedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted {0} file.
        /// </summary>
        public static string MsgDeletedItems1 {
            get {
                return ResourceManager.GetString("MsgDeletedItems1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted {0} files.
        /// </summary>
        public static string MsgDeletedItems2 {
            get {
                return ResourceManager.GetString("MsgDeletedItems2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to directory not found.
        /// </summary>
        public static string MsgDirectoryNotFound {
            get {
                return ResourceManager.GetString("MsgDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to archive is empty.
        /// </summary>
        public static string MsgEmptyArchive {
            get {
                return ResourceManager.GetString("MsgEmptyArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error extracting file.
        /// </summary>
        public static string MsgErrorExtracting {
            get {
                return ResourceManager.GetString("MsgErrorExtracting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening file.
        /// </summary>
        public static string MsgErrorOpening {
            get {
                return ResourceManager.GetString("MsgErrorOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracted {0} into {1}.
        /// </summary>
        public static string MsgExtractComplete {
            get {
                return ResourceManager.GetString("MsgExtractComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracted {0} file.
        /// </summary>
        public static string MsgExtractedFiles1 {
            get {
                return ResourceManager.GetString("MsgExtractedFiles1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracted {0} files.
        /// </summary>
        public static string MsgExtractedFiles2 {
            get {
                return ResourceManager.GetString("MsgExtractedFiles2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting files from {0}.
        /// </summary>
        public static string MsgExtractingArchive {
            get {
                return ResourceManager.GetString("MsgExtractingArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting file from {0}.
        /// </summary>
        public static string MsgExtractingFile {
            get {
                return ResourceManager.GetString("MsgExtractingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting files from {0} to {1}.
        /// </summary>
        public static string MsgExtractingTo {
            get {
                return ResourceManager.GetString("MsgExtractingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} file.
        /// </summary>
        public static string MsgFiles1 {
            get {
                return ResourceManager.GetString("MsgFiles1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files.
        /// </summary>
        public static string MsgFiles2 {
            get {
                return ResourceManager.GetString("MsgFiles2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image {0} x {1} x {2}bpp.
        /// </summary>
        public static string MsgImageSize {
            get {
                return ResourceManager.GetString("MsgImageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no files to extract.
        /// </summary>
        public static string MsgNoFiles {
            get {
                return ResourceManager.GetString("MsgNoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0}
        ///already exists.
        ///
        ///Overwrite?.
        /// </summary>
        public static string MsgOverwrite {
            get {
                return ResourceManager.GetString("MsgOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string MsgReady {
            get {
                return ResourceManager.GetString("MsgReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unable to interpret image format.
        /// </summary>
        public static string MsgUnableInterpret {
            get {
                return ResourceManager.GetString("MsgUnableInterpret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file could not be opened as resource archive.
        /// </summary>
        public static string MsgUnknownFormat {
            get {
                return ResourceManager.GetString("MsgUnknownFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string MsgVersion {
            get {
                return ResourceManager.GetString("MsgVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [builtin].
        /// </summary>
        public static string TextAboutBuiltin {
            get {
                return ResourceManager.GetString("TextAboutBuiltin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported archives:.
        /// </summary>
        public static string TextAboutSupportedArchives {
            get {
                return ResourceManager.GetString("TextAboutSupportedArchives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported image formats:.
        /// </summary>
        public static string TextAboutSupportedImages {
            get {
                return ResourceManager.GetString("TextAboutSupportedImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Game Resource browser.
        /// </summary>
        public static string TextAboutTitle {
            get {
                return ResourceManager.GetString("TextAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files.
        /// </summary>
        public static string TextAllFiles {
            get {
                return ResourceManager.GetString("TextAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to as is.
        /// </summary>
        public static string TextAsIs {
            get {
                return ResourceManager.GetString("TextAsIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose archive location.
        /// </summary>
        public static string TextChooseArchive {
            get {
                return ResourceManager.GetString("TextChooseArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose destination directory.
        /// </summary>
        public static string TextChooseDestDir {
            get {
                return ResourceManager.GetString("TextChooseDestDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm overwrite.
        /// </summary>
        public static string TextConfirmOverwrite {
            get {
                return ResourceManager.GetString("TextConfirmOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create archive.
        /// </summary>
        public static string TextCreateArchive {
            get {
                return ResourceManager.GetString("TextCreateArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive creation error.
        /// </summary>
        public static string TextCreateArchiveError {
            get {
                return ResourceManager.GetString("TextCreateArchiveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete files.
        /// </summary>
        public static string TextDeleteFiles {
            get {
                return ResourceManager.GetString("TextDeleteFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text encoding.
        /// </summary>
        public static string TextEncoding {
            get {
                return ResourceManager.GetString("TextEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract images.
        /// </summary>
        public static string TextExtractImages {
            get {
                return ResourceManager.GetString("TextExtractImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract text.
        /// </summary>
        public static string TextExtractText {
            get {
                return ResourceManager.GetString("TextExtractText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract from archive.
        /// </summary>
        public static string TextExtractTitle {
            get {
                return ResourceManager.GetString("TextExtractTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive parameters.
        /// </summary>
        public static string TextParametersTitle {
            get {
                return ResourceManager.GetString("TextParametersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        public static string TextSaveAs {
            get {
                return ResourceManager.GetString("TextSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save images as.
        /// </summary>
        public static string TextSaveImagesAs {
            get {
                return ResourceManager.GetString("TextSaveImagesAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Resource browser.
        /// </summary>
        public static string TextTitle {
            get {
                return ResourceManager.GetString("TextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string TooltipBack {
            get {
                return ResourceManager.GetString("TooltipBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        public static string TooltipForward {
            get {
                return ResourceManager.GetString("TooltipForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DIR&gt;.
        /// </summary>
        public static string Type_directory {
            get {
                return ResourceManager.GetString("Type_directory", resourceCulture);
            }
        }
    }
}
